config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:show, :index]
  resources :responses, only: [:show, :index]

  root to: 'creative_qualities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creative_quality.rb
class CreativeQuality < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  enum color: {
    primary: 0,
    danger: 1,
    success: 2,
    info: 3,
    warning: 4
  }
  validates :color, uniqueness: true, presence: true

  after_initialize :init_color

  def init_color
    if self.color.blank?
      potential_colors = (0..4).to_a
      existing_colors = CreativeQuality.all.map{ |c| c.color }
      free_colors = potential_colors.select{ |cdx| existing_colors.exclude?(cdx) }
      self.color = free_colors.sample
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices, class_name: 'QuestionChoice', inverse_of: :question

  validates :title, presence: true

  accepts_nested_attributes_for(:choices)
end

app/models/question_choice.rb
class QuestionChoice < ApplicationRecord
  belongs_to :question, inverse_of: :choices
  belongs_to :creative_quality

  validates :text, presence: true
  validates :question, presence: true
  validates :creative_quality, presence: true
  validates :score, numericality: { only_integer: true }
end

app/models/question_response.rb
class QuestionResponse < ApplicationRecord
  belongs_to :question_choice
  belongs_to :response

  validates :question_choice, presence: true
  validates :response, presence: true

  delegate :question, to: :question_choice
end

app/models/response.rb
class Response < ApplicationRecord
  has_many :question_responses

  validates :first_name, presence: true
  validates :last_name, presence: true

  delegate :count, to: :question_responses, prefix: true

  def display_name
    "#{first_name} #{last_name}"
  end

  def completed?
    question_responses_count == Question.count
  end

  def responses_by_creative_quality(creative_quality)
    self.question_responses.select do |question_response|
      question_response.question_choice.creative_quality ==
        creative_quality
    end
  end

  def scores_by_creative_quality(creative_quality)
    self.responses_by_creative_quality(creative_quality).map {
      |question_response| question_response.question_choice.score
    }
  end

  def norm_by_creative_quality(creative_quality)
    raw = self.scores_by_creative_quality(creative_quality).reduce(0, :+)
    min = self.min_by_creative_quality(creative_quality)
    max = self.max_by_creative_quality(creative_quality)
    self.normalize_score(raw, min, max)
  end

  def min_by_creative_quality(creative_quality)
    total_choices = self.choice_scores_by_creative_quality(
      creative_quality)
    total_choices.reduce(0) {|acc, choices| acc + choices.min}
  end

  def max_by_creative_quality(creative_quality)
    total_choices = self.choice_scores_by_creative_quality(
      creative_quality)
    total_choices.reduce(0) {|acc, choices| acc + choices.max}
  end

  protected
  def choice_scores_by_creative_quality(creative_quality)
    totals = []
    self.responses_by_creative_quality(creative_quality).each {
      |question_response|
      total_q_r = []
      question_response.question.choices.each { |choice|
        total_q_r.push(choice.score)
      }
      totals.push(total_q_r)
    }
    return totals
  end

  def normalize_score(raw_score, min_score, max_score)
    raw = raw_score.to_f
    min = min_score.to_f
    max = max_score.to_f
    ((min.abs + raw) / (min.abs + max) * 100.0).round
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creative_qualities_controller.rb
class CreativeQualitiesController < ApplicationController
  def index
    @creative_qualities = CreativeQuality.all
    @responses = Response
      .includes(question_responses: [question_choice: [question: :choices]])
      .all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.includes(:choices).find(params[:id])
  end

  def index
    @questions = Question.order(:id)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def show
    @response = Response
      .includes(question_responses: [question_choice: [question: :choices]])
      .find(params[:id])
    @creative_qualities = CreativeQuality.all
  end

  def index
    @responses = Response.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creative_qualities/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>
      Creative Qualities
    </h2>

    <div class="row">
      <%= @creative_qualities.find_each do |creative_quality| %>
        <div class="col-md-4">
          <div class="panel panel-<%= creative_quality.color %>">
            <div class="panel-heading">
              <%= creative_quality.name %>
            </div>

            <div class="panel-body">
              <p>
                <%= creative_quality.description %>
              </p>

              <hr>

              <%
                total = @responses.map {|response| response.norm_by_creative_quality(
                  creative_quality)}.reduce(0, :+)
                avg = (total / Response.count.to_f).round
              %>
              <div class="progress">
                <div class="progress-bar bg-<%= creative_quality.color %>" role="progressbar"
                  style="width: <%= avg %>%"
                  aria-valuenow="<%= avg %>" aria-valuemin="0" aria-valuemax="100">
                </div>
              </div>
              <p>
                <strong>Your Score: <%= avg %></strong>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div style="padding: 100px 0;">
  <hr>

  <small class="text-muted">
    Thoughtfully designed by IDEO in California.
  </small>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Creative Difference', root_path, class: 'navbar-brand' %>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="navbar-nav nav">
        <li>
          <%= link_to 'Questions', questions_path %>
        </li>

        <li>
          <%= link_to 'Responses', responses_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Creative Difference – IDEO</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notifications' %>

    <div class="container">
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/questions/_header.html.erb
<h3>
  <div>
    <strong>
      <%= "Question #{question.id}" %>
    </strong>
  </div>

  <%= question.title %>
</h3>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      Questions
    </h2>

    <table class="table">
      <tbody>
        <% @questions.find_each do |question| %>
          <tr>
            <td>
              <strong>
                <%= question.id %>.
              </strong>
            </td>

            <td>
              <%= truncate(question.title, length: 75) %>
            </td>

            <td>
              <%= link_to 'View', question_path(question), class: 'btn btn-default btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-7">
    <%= render 'questions/header', question: @question %>

    <hr>

    <h3>
      Choices
    </h3>

    <%= bootstrap_form_for(@question) do |question_form| %>
      <table class="table">
        <% @question.choices.each_with_index do |choice, index| %>
          <% hide_label = index > 0 %>

          <%= question_form.fields_for(:choices, choice) do |choice_fields| %>
            <tr>
              <td>
                <%= choice_fields.text_field :text, readonly: true, hide_label: hide_label %>
              </td>

              <td>
                <%= choice_fields.select :creative_quality_id, options_for_select(CreativeQuality.pluck(:name, :id)), { hide_label: hide_label }, { disabled: true } %>
              </td>

              <td>
                <%= choice_fields.text_field :score, readonly: true, hide_label: hide_label %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>

      <div class="text-right">
        <%= question_form.submit 'Update Choices', disabled: true %>
      </div>
    <% end %>
  </div>
</div>

app/views/responses/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      Responses
    </h2>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Completed?</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @responses.find_each do |response| %>
          <tr>
            <td>
              <%= truncate(response.display_name, length: 90) %>
            </td>

            <td>
              <% if response.completed? %>
                Yes
              <% else %>
                <span class="text-danger">No</span>
              <% end %>
            </td>

            <td>
              <%= link_to 'View', response_path(response), class: 'btn btn-default btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/responses/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>
          <%= @response.display_name %>
        </h3>
      </div>

      <div class="panel-body">
        Completed
        <%= @response.question_responses_count %>
        of
        <%= Question.count %>
        questions
      </div>
    </div>

    <hr>

    <% @creative_qualities.each do |creative_quality| %>
      <h4 class="text-<%= creative_quality.color %>">
        <%= creative_quality.name %> -
        <%= @response.norm_by_creative_quality(creative_quality) %>
      </h4>
      <ul>
        <li>
          Raw score:
          <%= @response.scores_by_creative_quality(creative_quality).reduce(0, :+) %>
        </li>
        <li>
          Min score: <%= @response.min_by_creative_quality(creative_quality) %>
        </li>
        <li>
          Max score: <%= @response.max_by_creative_quality(creative_quality) %>
        </li>
      </ul>

    <% end %>

    <% @response.question_responses.each do |question_response| %>
      <%= render 'questions/header', question: question_response.question %>

      <table class="table table-bordered">
        <% question_response.question.choices.each do |question_choice| %>
          <tr>
            <td>
              <% if question_choice == question_response.question_choice %>
                <strong>
                  <%= question_choice.text %>
                </strong><br />
                <% color = question_choice.score >= 0 ? "success" : "danger" %>
                <span class="text-<%= color %>">
                  <%= question_choice.creative_quality.name %>
                  <%= question_choice.score %>
                </span>
              <% else %>
                <span class="text-muted">
                  <%= question_choice.text %><br />
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>